version: '3.9'

services:
  postgres:
    container_name: postgressearchapp
    image: postgres:latest
    environment:
      POSTGRES_DB: "search_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5401:5432"

  elasticsearch:
    image: mirror.gcr.io/library/elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"